<a href="https://colab.research.google.com/github/heodabin/Linear-Algebra2/blob/main/%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


#### 라이브러리(패키지)로드

In [3]:
import numpy as np

### 2.벡터, 행렬 연산, 그래프 그리기
##### 프린트

In [4]:
def print_val(x):
    print("Type:", type(x))
    print("Shape:", x.shape)
    print("값: \n", x)
    print(" ")

In [7]:
x= np.array([1,2,3])
print_val(x)

x[0]=5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [5 2 3]
 


In [8]:
y=np.array([[1,2,3],[4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값: 
 [[1 2 3]
 [4 5 6]]
 


In [11]:
a=np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [12]:
a=np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값: 
 [[0. 0.]
 [0. 0.]]
 


In [13]:
a=np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [14]:
a=np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[0.869903   0.52244158 0.03395284 0.58267093]
 [0.73234174 0.47816758 0.09676764 0.86367772]
 [0.19425008 0.15066798 0.1654196  0.60201547]
 [0.81549356 0.41386313 0.19916658 0.69183221]]
 


In [17]:
a=np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[-2.18754968  0.35790025 -2.06891219  0.06584488]
 [-0.67707747  0.29367193  1.65340913 -0.05301858]
 [-0.4583745  -0.48723762 -1.28004039  1.10215594]
 [ 1.18919462 -1.21503893  0.73695205 -0.32777087]]
 
